### ISSUE TITLE
Variable setting value in OnInitializedAsync

### ISSUE THREAD

**Issue by pablokentch** [simonziegler/BlazorMdc#572]
**Describe the bug**
I have an MBTextField field where I need to set the value in an OnInitializedAsync

**My code for example**

```
<MBTextField Value = "@MyName" Label="Name" TextInputStyle="MBTextInputStyle.Filled" @oninput="() => SetName()"/>

@code {
     private string MyName { get; set; }

     protected override async Task OnInitializedAsync() {
           var name = await info.GetNameAsync<string>("Name");
           MyName  = name;
     }
     ...
}
```
The var just doesn't seem to be defined it doesn't update the `MBTextField `value

and the `info.GetNameAsync<string>("Name")` function is working because I used a `MessageBox` and it returns me correctly.

**Comment by RichardWalace** [comment]
I have the same problem the difference is that I am using localstorage.

I tested it with another api like mudblazor and it works well, but in the material  blazor it has this problem, I like the material 
 blazor because it is more faithful to the details of the material web.

@simonziegler know something about it?

**Comment by MarkStega** [comment]
A big difference between MudBlazor & Material.Blazor is that we use the Material javascript in all of our components, MudBlazor uses extensive css to mimic Material.

Look at our demo site, the proper two way binding to a value is to use @bind-Value. However, setting values inside the component itself is very tricky because of the js and interactions that may occur.

Look at the code repository for Material.Blazor and examine all of the issues that we solved in Foundation/InputComponent.cs; You have to do all of that to successfully set a value from 'inside' a component.

**Comment by RichardWalace** [comment]
@MarkStega I use `@bind-Value` and it still happens the problem here only occurs in `async` functions

and I think you guys should look at it better and not close the problem like that.

Did you test what was reported here?

**Comment by MarkStega** [comment]
No, we didn't test the scenario because we don't expect it to work; You really need to understand the interactions of Blazor & Material when you start trying to change values from inside of a component. That's why I suggested a study of Foundation/InputComponent.cs as a starting point.
